language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk7
script:
  - cp -r ./hannanum/models/* ./
  - sbt -J-Xmx4g ++2.11.8 eunjeon/test
  - sbt -J-Xmx4g ++$TRAVIS_SCALA_VERSION core/test
  - sbt -J-Xmx4g ++$TRAVIS_SCALA_VERSION komoran/test
  - sbt -J-Xmx4g ++$TRAVIS_SCALA_VERSION kkma/test
  - sbt -J-Xmx4g ++$TRAVIS_SCALA_VERSION twitter/test
  - sbt -J-Xmx4g ++$TRAVIS_SCALA_VERSION hannanum/test
  - sbt -J-Xmx4g ++$TRAVIS_SCALA_VERSION rest/test