language: scala
scala:
  - 2.11.8
install:
  - cp -r ./hannanum/models/* ./
script:
  - sbt -J-Xmx4g ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate
after_success:
  - bash <(curl -s https://codecov.io/bash)
